include_product_features: false
include_kiosk_features: true
include_behavioral_features: true
include_personalization_features: false
include_popularity_features: false
include_seasonality_features: true
encode_channel: false
encode_region: false
